"""
OphAgent Planner.

Converts a natural-language clinical query into a structured, ordered
execution plan (list of tool-call steps).  The plan is generated by the LLM
backbone conditioned on the available tool registry.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from ophagent.llm.backbone import LLMBackbone
from ophagent.llm.prompts import PromptLibrary
from ophagent.utils.logger import get_logger
from ophagent.utils.text_utils import extract_json_block

logger = get_logger("core.planner")


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class PlanStep:
    step_id: int
    tool_name: str
    inputs: Dict[str, Any]
    description: str
    depends_on: List[int] = field(default_factory=list)


@dataclass
class ExecutionPlan:
    query: str
    steps: List[PlanStep]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def get_step(self, step_id: int) -> Optional[PlanStep]:
        for s in self.steps:
            if s.step_id == step_id:
                return s
        return None

    def topological_order(self) -> List[PlanStep]:
        """Return steps in dependency-safe execution order (Kahn's algorithm)."""
        from collections import deque
        in_degree = {s.step_id: 0 for s in self.steps}
        graph: Dict[int, List[int]] = {s.step_id: [] for s in self.steps}
        for s in self.steps:
            for dep in s.depends_on:
                graph[dep].append(s.step_id)
                in_degree[s.step_id] += 1

        queue = deque(sid for sid, deg in in_degree.items() if deg == 0)
        order: List[PlanStep] = []
        id_to_step = {s.step_id: s for s in self.steps}

        while queue:
            sid = queue.popleft()
            order.append(id_to_step[sid])
            for neighbour in graph[sid]:
                in_degree[neighbour] -= 1
                if in_degree[neighbour] == 0:
                    queue.append(neighbour)

        if len(order) != len(self.steps):
            logger.warning("Execution plan has a cycle; falling back to linear order.")
            return self.steps
        return order


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------

class Planner:
    """
    Given a user query and session context, produces an ExecutionPlan.

    The LLM backbone generates the plan as JSON; this class validates and
    wraps it into typed PlanStep / ExecutionPlan objects.
    """

    def __init__(self, llm: Optional[LLMBackbone] = None):
        self.llm = llm or LLMBackbone()
        self._tool_descriptions: Optional[str] = None

    # ------------------------------------------------------------------
    # Tool description helpers
    # ------------------------------------------------------------------

    def _load_tool_descriptions(self) -> str:
        """Build a concise tool description string from the registry YAML."""
        if self._tool_descriptions:
            return self._tool_descriptions

        import yaml
        from config.settings import get_settings
        registry_path = get_settings().tools.tool_registry_path
        if not registry_path.exists():
            return "No tool registry found."

        with open(registry_path, encoding="utf-8") as f:
            registry = yaml.safe_load(f)

        lines = []
        for tool_id, meta in registry.get("tools", {}).items():
            lines.append(
                f"- {tool_id}: {meta.get('description', '')} "
                f"[modality={meta.get('modality')}, task={meta.get('task')}]"
            )
        self._tool_descriptions = "\n".join(lines)
        return self._tool_descriptions

    # ------------------------------------------------------------------
    # Plan generation
    # ------------------------------------------------------------------

    def plan(
        self,
        query: str,
        image_paths: Optional[List[str]] = None,
        session_context: Optional[str] = None,
    ) -> ExecutionPlan:
        """
        Generate an ExecutionPlan for *query*.

        Args:
            query: Natural-language clinical or research question.
            image_paths: Optional list of image file paths provided by the user.
            session_context: Formatted string of recent session history.

        Returns:
            ExecutionPlan with validated steps.
        """
        image_context = "\n".join(image_paths or []) or "No images provided."
        session_ctx = session_context or "First query in session."
        tool_desc = self._load_tool_descriptions()

        system = PromptLibrary.planner_system(tool_desc)
        user_msg = PromptLibrary.planner_user(
            query=query,
            image_context=image_context,
            session_context=session_ctx,
        )

        logger.info(f"Planning query: {query[:80]}...")
        raw = self.llm.chat_json(
            [{"role": "user", "content": user_msg}],
            system=system,
            temperature=0.0,
        )

        steps = self._parse_steps(raw)
        plan = ExecutionPlan(query=query, steps=steps)
        logger.info(f"Plan generated with {len(steps)} steps.")
        return plan

    # ------------------------------------------------------------------
    # Parsing helpers
    # ------------------------------------------------------------------

    def _parse_steps(self, raw: dict) -> List[PlanStep]:
        """Validate and convert raw dict steps to PlanStep objects."""
        raw_steps = raw.get("steps", [])
        if not raw_steps:
            logger.warning("Planner returned no steps; inserting fallback search step.")
            return [PlanStep(
                step_id=1,
                tool_name="web_search",
                inputs={"query": "ophthalmic guidance"},
                description="Fallback: search for relevant clinical guidance",
                depends_on=[],
            )]

        steps = []
        for s in raw_steps:
            steps.append(PlanStep(
                step_id=int(s.get("step_id", len(steps) + 1)),
                tool_name=str(s.get("tool_name", "web_search")),
                inputs=s.get("inputs", {}),
                description=str(s.get("description", "")),
                depends_on=[int(d) for d in s.get("depends_on", [])],
            ))
        return steps

    # ------------------------------------------------------------------
    # Re-planning (called by Verifier on conflict)
    # ------------------------------------------------------------------

    def replan(
        self,
        original_plan: ExecutionPlan,
        conflict_description: str,
    ) -> ExecutionPlan:
        """
        Generate a revised plan given a description of conflicts found
        by the Verifier.
        """
        amended_query = (
            f"{original_plan.query}\n\n"
            f"Note: The previous plan had conflicts: {conflict_description}\n"
            "Please revise the plan to resolve these issues."
        )
        return self.plan(amended_query)
